export const routes = {
  dashboard: "/",
  dispatch: {
    overview: "/dispatch",
    home: "/dispatch",
    liveMap: "/dispatch/live-map",
    scheduledRides: "/dispatch/scheduled-rides",
    manualDispatch: "/dispatch/manual-dispatch",
  },
  fleet: {
    overview: "/fleet",
    home: "/fleet",
    drivers: "/fleet/drivers",
    driverApplications: "/fleet/driver-applications",
    driverDocuments: "/fleet/driver-documents",
    driverIncentives: "/fleet/driver-incentives",
    driverPayouts: "/fleet/driver-payouts",
    vehicles: "/fleet/vehicles",
  },
  sales: {
    overview: "/sales",
    home: "/sales/invoices",
    orders: "/sales/orders",
    invoices: "/sales/invoices",
    payments: "/sales/payments",
    customers: "/sales/customers",
    refunds: "/sales/refunds",
    payouts: "/sales/payouts",
  },
  logistics: {
    overview: "/logistics",
    home: "/logistics",
    shipments: "/logistics/shipments",
    tracking: "/logistics/tracking",
    drivers: "/logistics/drivers",
    exceptions: "/logistics/exceptions",
    zones: "/logistics/zones-geofencing",
    serviceTypes: "/logistics/service-types",
    pricing: "/logistics/pricing-commission",
  },
  marketplace: {
    overview: "/marketplace",
    home: "/marketplace",
    vendorApplications: "/marketplace/vendor-applications",
    products: "/marketplace/products",
    vendors: "/marketplace/vendors",
    categories: "/marketplace/categories",
    reviews: "/marketplace/reviews",
  },
  crm: {
    overview: "/crm",
    home: "/crm",
    customers: "/crm/customers",
    riders: "/crm/riders",
    corporateAccounts: "/crm/corporate-accounts",
    wallets: "/crm/wallets",
    ratingsReviews: "/crm/ratings-reviews",
    blockedUsers: "/crm/blocked-users",
  },
  supportDesk: {
    overview: "/support",
    home: "/support/inbox",
    inbox: "/support/inbox",
    tickets: "/support/tickets",
    escalations: "/support/escalations",
    disputes: "/support/disputes",
  },
  risk: {
    overview: "/risk",
    home: "/risk",
    fraud: "/risk/fraud-risk",
    emergency: "/risk/sos-emergency",
    compliance: "/risk/safety-compliance",
  },
  growth: {
    overview: "/growth",
    home: "/growth",
    promotions: "/growth/promotions",
    campaigns: "/growth/driver-incentives",
    notifications: "/growth/notifications",
  },
  platform: {
    overview: "/platform",
    home: "/platform",
    reports: "/platform/reports-analytics",
    content: "/platform/content-management",
    appControl: "/platform/app-version-control",
    health: "/platform/system-health",
    adminUsers: "/platform/admin-users",
    activityLogs: "/platform/admin-activity-logs",
    settings: "/platform/settings",
  },
  orders: "/orders",
  deliveries: "/deliveries",
  catalog: "/catalog",
  customers: "/crm/customers",
  drivers: "/drivers",
  vendors: "/vendors",
  content: "/content",
  support: "/support",
  settings: "/settings",
  profile: "/profile",
  signIn: "/signin",
};
