export const routes = {
  dashboard: "/",
  sales: {
    home: "/sales/invoices",
    orders: "/sales/orders",
    invoices: "/sales/invoices",
    customers: "/sales/customers",
    refunds: "/sales/refunds",
  },
  logistics: {
    home: "/logistics",
    shipments: "/logistics/shipments",
    tracking: "/logistics/tracking",
    drivers: "/logistics/drivers",
  },
  marketplace: {
    home: "/marketplace",
    products: "/marketplace/products",
    vendors: "/marketplace/vendors",
    categories: "/marketplace/categories",
  },
  supportDesk: {
    home: "/support/inbox",
    inbox: "/support/inbox",
    tickets: "/support/tickets",
    escalations: "/support/escalations",
  },
  orders: "/orders",
  deliveries: "/deliveries",
  catalog: "/catalog",
  customers: "/customers",
  drivers: "/drivers",
  vendors: "/vendors",
  content: "/content",
  support: "/support",
  settings: "/settings",
  profile: "/profile",
  signIn: "/signin",
};
