export const routes = {
  auth: {
    signIn: "/signin",
    forgotPassword1: "/auth/forgot-password-1",
    otp1: "/auth/otp-1",
  },
  dashboard: "/",
  dispatch: {
    overview: "/dispatch",
    home: "/dispatch",
    liveMap: "/dispatch/live-map",
    scheduledRides: "/dispatch/scheduled-rides",
    manualDispatch: "/dispatch/manual-dispatch",
  },
  fleet: {
    overview: "/fleet",
    home: "/fleet",
    drivers: "/fleet/drivers",
    driverApplications: "/fleet/driver-applications",
    driverDocuments: "/fleet/driver-documents",
    driverIncentives: "/fleet/driver-incentives",
    driverPayouts: "/fleet/driver-payouts",
    vehicles: "/fleet/vehicles",
  },
  sales: {
    overview: "/sales",
    home: "/sales/invoices",
    orders: "/sales/orders",
    createOrder: "/sales/orders/create",
    orderDetails: (id: string) => `/sales/orders/${id}`,
    editOrder: (id: string) => `/sales/orders/${id}/edit`,
    invoices: "/sales/invoices",
    createInvoice: "/sales/invoices/create",
    invoiceDetails: (id: string) => `/sales/invoices/${id}`,
    editInvoice: (id: string) => `/sales/invoices/${id}/edit`,
    invoiceBuilder: "/sales/invoices/builder",
    payments: "/sales/payments",
    customers: "/sales/customers",
    refunds: "/sales/refunds",
    payouts: "/sales/payouts",
  },
  logistics: {
    overview: "/logistics",
    home: "/logistics",
    shipments: "/logistics/shipments",
    createShipment: "/logistics/shipments/create",
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    tracking: "/logistics/tracking",
    trackingDetails: (id: string) => `/logistics/tracking/${id}`,
    drivers: "/logistics/drivers",
    exceptions: "/logistics/exceptions",
    zones: "/logistics/zones-geofencing",
    serviceTypes: "/logistics/service-types",
    pricing: "/logistics/pricing-commission",
  },
  marketplace: {
    overview: "/marketplace",
    home: "/marketplace",
    vendorApplications: "/marketplace/vendor-applications",
    products: "/marketplace/products",
    createProduct: "/marketplace/products/create",
    productDetails: (slug: string) => `/marketplace/products/${slug}`,
    editProduct: (slug: string) => `/marketplace/products/${slug}/edit`,
    vendors: "/marketplace/vendors",
    createVendor: "/marketplace/vendors/create",
    vendorDetails: (slug: string) => `/marketplace/vendors/${slug}`,
    editVendor: (slug: string) => `/marketplace/vendors/${slug}/edit`,
    categories: "/marketplace/categories",
    createCategory: "/marketplace/categories/create",
    editCategory: (id: string) => `/marketplace/categories/${id}/edit`,
    reviews: "/marketplace/reviews",
  },
  crm: {
    overview: "/crm",
    home: "/crm",
    customers: "/crm/customers",
    riders: "/crm/riders",
    corporateAccounts: "/crm/corporate-accounts",
    wallets: "/crm/wallets",
    ratingsReviews: "/crm/ratings-reviews",
    blockedUsers: "/crm/blocked-users",
  },
  supportDesk: {
    overview: "/support",
    home: "/support/inbox",
    inbox: "/support/inbox",
    tickets: "/support/tickets",
    escalations: "/support/escalations",
    disputes: "/support/disputes",
    templates: "/support/templates",
    createTemplate: "/support/templates/create",
    templateDetails: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  risk: {
    overview: "/risk",
    home: "/risk",
    fraud: "/risk/fraud-risk",
    emergency: "/risk/sos-emergency",
    compliance: "/risk/safety-compliance",
  },
  growth: {
    overview: "/growth",
    home: "/growth",
    promotions: "/growth/promotions",
    campaigns: "/growth/driver-incentives",
    notifications: "/growth/notifications",
  },
  platform: {
    overview: "/platform",
    home: "/platform",
    reports: "/platform/reports-analytics",
    content: "/platform/content-management",
    appControl: "/platform/app-version-control",
    health: "/platform/system-health",
    adminUsers: "/platform/admin-users",
    activityLogs: "/platform/admin-activity-logs",
    settings: "/platform/settings",
  },
  rolesPermissions: "/roles-permissions",
  orders: "/orders",
  deliveries: "/deliveries",
  catalog: "/catalog",
  customers: "/crm/customers",
  drivers: "/drivers",
  vendors: "/vendors",
  content: "/content",
  support: "/support",
  settings: "/settings",
  emailTemplates: "/email-templates",
  profile: "/profile",
  signIn: "/signin",
};
