"use client";

import type { AdminStatus, AdminTimelineEntry } from "@/contracts/admin-domain";

export type CustomerProfile = {
  id: string;
  name: string;
  email: string;
  phone: string;
  segment: string;
  status: AdminStatus;
  city: string;
  address: string;
  owner: string;
  joinedAt: string;
  updatedAt: string;
  walletBalance: string;
  lifetimeSpend: string;
  totalOrders: string;
  completedOrders: string;
  cancelledOrders: string;
  lastOrder: string;
  appVersion: string;
  paymentMethod: string;
  notes: string;
  tags: string[];
  timeline: AdminTimelineEntry[];
};

export const customerProfiles: CustomerProfile[] = [
  {
    id: "CUS-876",
    name: "Loveness Phiri",
    email: "loveness.phiri@ntumai.test",
    phone: "+260 97 721 0188",
    segment: "Refund recovery",
    status: "review",
    city: "Lusaka",
    address: "Libala South, Lusaka",
    owner: "Care pod",
    joinedAt: "06 Feb 2025",
    updatedAt: "29 Apr 2026, 09:28",
    walletBalance: "ZMW 38",
    lifetimeSpend: "ZMW 3,460",
    totalOrders: "41",
    completedOrders: "34",
    cancelledOrders: "7",
    lastOrder: "Today, 09:18",
    appVersion: "Customer App v5.18.0",
    paymentMethod: "Card ending 2204",
    notes: "Customer is in active refund recovery after repeated missing-item and delayed-settlement contacts.",
    tags: ["Refund recovery", "Wallet follow-up"],
    timeline: [
      { label: "Refund case opened", detail: "Support and finance are tracing a recent recovery request.", time: "09:28" },
      { label: "Missing-items claim logged", detail: "Customer disputed a completed delivery over missing items.", time: "Today" },
      { label: "Wallet follow-up attached", detail: "Recent case notes were added to the CRM profile.", time: "Yesterday" },
    ],
  },
  {
    id: "CUS-875",
    name: "Chisomo Tembo",
    email: "chisomo.tembo@ntumai.test",
    phone: "+260 96 900 4512",
    segment: "Service recovery",
    status: "monitoring",
    city: "Kitwe",
    address: "Nkana East, Kitwe",
    owner: "Success team",
    joinedAt: "14 Oct 2024",
    updatedAt: "29 Apr 2026, 09:12",
    walletBalance: "ZMW 24",
    lifetimeSpend: "ZMW 5,280",
    totalOrders: "63",
    completedOrders: "57",
    cancelledOrders: "6",
    lastOrder: "Today, 08:48",
    appVersion: "Customer App v5.18.0",
    paymentMethod: "Visa ending 1930",
    notes: "High-touch recovery profile after repeated lateness and delivery-dispute complaints across recent orders.",
    tags: ["VIP recovery", "Late delivery"],
    timeline: [
      { label: "Recovery watch refreshed", detail: "Support lead kept the customer in same-day care after multiple failed experiences.", time: "09:12" },
      { label: "Delivery dispute linked", detail: "Support moved a wrong-handoff case into disputes.", time: "Today" },
      { label: "Chargeback notice noted", detail: "Finance added issuer-side dispute context to the profile.", time: "Yesterday" },
    ],
  },
  {
    id: "CUS-874",
    name: "Agnes Mumba",
    email: "agnes.mumba@ntumai.test",
    phone: "+260 96 311 8044",
    segment: "Payments review",
    status: "at_risk",
    city: "Kabwe",
    address: "Railway, Kabwe",
    owner: "Finance care",
    joinedAt: "02 Dec 2024",
    updatedAt: "29 Apr 2026, 08:24",
    walletBalance: "ZMW 0",
    lifetimeSpend: "ZMW 2,740",
    totalOrders: "33",
    completedOrders: "25",
    cancelledOrders: "8",
    lastOrder: "Today, 08:02",
    appVersion: "Customer App v5.17.6",
    paymentMethod: "Wallet + card split",
    notes: "Customer remains on payment-risk watch while finance validates duplicate-charge and refund-release issues.",
    tags: ["Duplicate charge", "Finance hold"],
    timeline: [
      { label: "Payment risk attached", detail: "Finance blocked automatic recovery pending gateway confirmation.", time: "08:24" },
      { label: "Duplicate charge reported", detail: "Customer raised a retry-related payments complaint.", time: "Today" },
      { label: "Refund hold added", detail: "Support linked the open payment discrepancy to a pending refund case.", time: "Yesterday" },
    ],
  },
  {
    id: "CUS-873",
    name: "Brian Zulu",
    email: "brian.zulu@ntumai.test",
    phone: "+260 97 130 1228",
    segment: "Escalation care",
    status: "review",
    city: "Ndola",
    address: "Hillcrest, Ndola",
    owner: "Support lead",
    joinedAt: "28 Sep 2024",
    updatedAt: "29 Apr 2026, 07:44",
    walletBalance: "ZMW 16",
    lifetimeSpend: "ZMW 1,860",
    totalOrders: "22",
    completedOrders: "16",
    cancelledOrders: "6",
    lastOrder: "Today, 07:26",
    appVersion: "Customer App v5.17.8",
    paymentMethod: "MTN MoMo",
    notes: "Customer profile is under leadership review after repeated refund, lateness, and cancellation complaints.",
    tags: ["Leadership review", "Repeat complaints"],
    timeline: [
      { label: "Leadership review opened", detail: "Support escalated the account after repeated poor experiences.", time: "07:44" },
      { label: "Refund timing issue linked", detail: "Finance linked a recent auto-policy refund hold to the account.", time: "Today" },
      { label: "Delivery recovery noted", detail: "Customer became unreachable on a recent final-drop attempt.", time: "Yesterday" },
    ],
  },
  {
    id: "CUS-872",
    name: "Natasha Chinyama",
    email: "natasha.chinyama@ntumai.test",
    phone: "+260 97 844 1200",
    segment: "Trust dependency",
    status: "paused",
    city: "Lusaka",
    address: "Olympia, Lusaka",
    owner: "Trust support",
    joinedAt: "21 Nov 2024",
    updatedAt: "29 Apr 2026, 07:08",
    walletBalance: "ZMW 54",
    lifetimeSpend: "ZMW 3,980",
    totalOrders: "48",
    completedOrders: "39",
    cancelledOrders: "9",
    lastOrder: "Today, 06:44",
    appVersion: "Customer App v5.18.0",
    paymentMethod: "Wallet credit",
    notes: "Customer profile is paused behind a trust review that affects refund release and support closure paths.",
    tags: ["Trust dependency", "Abuse review"],
    timeline: [
      { label: "Trust hold applied", detail: "Support paused customer recovery while abuse review remains open.", time: "07:08" },
      { label: "Partial recovery proposed", detail: "Finance prepared a wallet credit pending trust clearance.", time: "Today" },
      { label: "Conduct complaint linked", detail: "Support attached chat-abuse evidence to the account.", time: "Yesterday" },
    ],
  },
  {
    id: "CUS-881",
    name: "Martha Bwalya",
    email: "martha.bwalya@ntumai.test",
    phone: "+260 97 330 1142",
    segment: "High value",
    status: "monitoring",
    city: "Lusaka",
    address: "Kabulonga, Lusaka",
    owner: "CRM desk",
    joinedAt: "12 Jan 2025",
    updatedAt: "29 Apr 2026, 09:04",
    walletBalance: "ZMW 186",
    lifetimeSpend: "ZMW 12,440",
    totalOrders: "148",
    completedOrders: "139",
    cancelledOrders: "9",
    lastOrder: "Today, 08:44",
    appVersion: "Customer App v5.18.0",
    paymentMethod: "Visa ending 1182",
    notes: "High-frequency groceries and marketplace buyer with recent inactivity trend after a support complaint cluster.",
    tags: ["VIP", "Wallet enabled", "Priority recovery"],
    timeline: [
      { label: "Customer profile reviewed", detail: "CRM opened retention watch after order cadence softened this week.", time: "09:04" },
      { label: "Support recovery applied", detail: "Wallet credit issued after delayed grocery handoff.", time: "Yesterday" },
      { label: "Marketplace purchase completed", detail: "Home essentials basket delivered successfully.", time: "27 Apr" },
    ],
  },
  {
    id: "CUS-880",
    name: "Josephine Mwila",
    email: "josephine.mwila@ntumai.test",
    phone: "+260 96 442 0081",
    segment: "Trust review",
    status: "review",
    city: "Ndola",
    address: "Itawa, Ndola",
    owner: "Trust team",
    joinedAt: "03 Mar 2025",
    updatedAt: "29 Apr 2026, 08:50",
    walletBalance: "ZMW 44",
    lifetimeSpend: "ZMW 2,910",
    totalOrders: "39",
    completedOrders: "31",
    cancelledOrders: "8",
    lastOrder: "28 Apr 2026, 19:18",
    appVersion: "Customer App v5.17.4",
    paymentMethod: "MTN MoMo",
    notes: "Wallet verification and manual KYC are still open before higher-value flows can be cleared.",
    tags: ["KYC review", "Wallet hold"],
    timeline: [
      { label: "Wallet verification opened", detail: "Finance requested manual customer verification before wallet release.", time: "08:50" },
      { label: "Customer submitted ID", detail: "Identity resubmission entered review queue.", time: "Yesterday" },
      { label: "Account restriction lifted partially", detail: "Ordering remains active while wallet actions stay gated.", time: "25 Apr" },
    ],
  },
  {
    id: "CUS-879",
    name: "Ciela Household",
    email: "ciela.household@ntumai.test",
    phone: "+260 95 220 4449",
    segment: "Weekly repeat",
    status: "stable",
    city: "Kitwe",
    address: "Parklands, Kitwe",
    owner: "Success team",
    joinedAt: "22 Aug 2024",
    updatedAt: "29 Apr 2026, 08:21",
    walletBalance: "ZMW 0",
    lifetimeSpend: "ZMW 8,760",
    totalOrders: "102",
    completedOrders: "99",
    cancelledOrders: "3",
    lastOrder: "Today, 07:55",
    appVersion: "Customer App v5.18.0",
    paymentMethod: "Airtel Money",
    notes: "Healthy repeat household with strong order cadence across groceries and quick errands.",
    tags: ["Healthy cadence", "Marketplace repeat"],
    timeline: [
      { label: "Repeat basket delivered", detail: "Scheduled grocery run completed within SLA.", time: "07:55" },
      { label: "Loyalty credit earned", detail: "Customer moved into the weekly repeat segment.", time: "Yesterday" },
      { label: "Profile refreshed", detail: "Address and preference data updated from recent orders.", time: "26 Apr" },
    ],
  },
  {
    id: "CUS-878",
    name: "Brian Tembo",
    email: "brian.tembo@ntumai.test",
    phone: "+260 97 114 3892",
    segment: "Refunds",
    status: "at_risk",
    city: "Lusaka",
    address: "Ibex Hill, Lusaka",
    owner: "Care pod",
    joinedAt: "14 Nov 2024",
    updatedAt: "29 Apr 2026, 08:00",
    walletBalance: "ZMW 62",
    lifetimeSpend: "ZMW 1,980",
    totalOrders: "27",
    completedOrders: "19",
    cancelledOrders: "8",
    lastOrder: "28 Apr 2026, 21:07",
    appVersion: "Customer App v5.16.9",
    paymentMethod: "Visa ending 4006",
    notes: "Customer has repeated refund follow-up contacts and needs recovery handling before churn risk grows further.",
    tags: ["Refund callbacks", "At risk"],
    timeline: [
      { label: "Refund follow-up logged", detail: "Customer called back about a missing wallet credit.", time: "08:00" },
      { label: "Finance note added", detail: "Refund desk confirmed the reversal is still pending settlement.", time: "Yesterday" },
      { label: "Retention watch opened", detail: "Support churn risk threshold was crossed.", time: "27 Apr" },
    ],
  },
  {
    id: "CUS-877",
    name: "Natasha Phiri",
    email: "natasha.phiri@ntumai.test",
    phone: "+260 97 411 2084",
    segment: "Growth",
    status: "live",
    city: "Lusaka",
    address: "Roma, Lusaka",
    owner: "Growth desk",
    joinedAt: "19 Apr 2026",
    updatedAt: "29 Apr 2026, 07:39",
    walletBalance: "ZMW 12",
    lifetimeSpend: "ZMW 480",
    totalOrders: "6",
    completedOrders: "6",
    cancelledOrders: "0",
    lastOrder: "28 Apr 2026, 18:14",
    appVersion: "Customer App v5.18.0",
    paymentMethod: "Cash on delivery",
    notes: "Newly onboarded referral customer with clean early usage and good conversion into first-week orders.",
    tags: ["Referral", "New user"],
    timeline: [
      { label: "Referral activation", detail: "Customer completed signup and first order journey.", time: "07:39" },
      { label: "First grocery order delivered", detail: "Initial conversion flow completed successfully.", time: "Yesterday" },
      { label: "Campaign attribution locked", detail: "Growth source confirmed for onboarding reporting.", time: "27 Apr" },
    ],
  },
];

export function getCustomerProfile(id: string) {
  return customerProfiles.find((customer) => customer.id === id);
}
